# docker-compose.db.yml

version: '3.8'

services:
  # The Database Service
  db:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.db
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql #
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis Service
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  # Trades Collector Service
  trades-collector:
    build:
      context: ./collectors/trades_collector
    container_name: trades-collector
    restart: always
    env_file:
      - .env.db
    depends_on:
      - redis

  # Order Book Collector Service
  book-collector:
    build:
      context: ./collectors/book_collector
    container_name: book-collector
    restart: always
    env_file:
      - .env.db
    depends_on:
      - redis

  # Writer Service
  writer:
    build:
      context: ./writer # Note: Create this new directory
    container_name: writer
    restart: always
    env_file:
      - .env.db
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  timescaledb-data: